version: '3.8'

services:
  # Nginx Gateway
  nginx-gateway:
    build: ./nginx-gateway
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
      - photo-service
      - chat-service
      - user-service
      - notification-service
      - admin-service
    networks:
      - phone-app-network

  # Auth Service
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - JWT_EXPIRES_IN=1h
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - BCRYPT_ROUNDS=12
      - API_KEY=phone-app-api-key-change-in-production
    depends_on:
      - mongo
    networks:
      - phone-app-network

  # Photo Service
  photo-service:
    build: ./services/photo-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb://mongo:27017/photos
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=photos
      - S3_REGION=us-east-1
      - MAX_FILE_SIZE=10485760
      - ALLOWED_MIME_TYPES=image/jpeg,image/png,image/webp
      - AUTH_SERVICE_URL=http://auth-service:3001
      - API_KEY=phone-app-api-key-change-in-production
    depends_on:
      - mongo
      - minio
      - auth-service
    networks:
      - phone-app-network

  chat-service:
    build: ./services/chat-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://mongo:27017/chat
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - REDIS_URL=redis://redis:6379
      - API_KEY=phone-app-api-key-change-in-production
    depends_on:
      - mongo
      - redis
    networks:
      - phone-app-network

  # User Service
  user-service:
    build: ./services/user-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGODB_URI=mongodb://mongo:27017/users
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
    depends_on:
      - mongo
    networks:
      - phone-app-network

  notification-service:
    build: ./services/notification-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MONGODB_URI=mongodb://mongo:27017/notifications
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
    depends_on:
      - mongo
    networks:
      - phone-app-network

  admin-service:
    build: ./services/admin-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - MONGODB_URI=mongodb://mongo:27017/admin
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - ADMIN_API_KEY=admin-api-key-change-in-production
      - ADMIN_ALLOWED_IPS=127.0.0.1,::1,172.18.0.1
      - ADMIN_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
    depends_on:
      - mongo
    networks:
      - phone-app-network

  # MongoDB
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - phone-app-network

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - phone-app-network

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - phone-app-network

volumes:
  mongo_data:
  redis_data:
  minio_data:

networks:
  phone-app-network:
    driver: bridge